name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cargo Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Deps
      run: sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends pkg-config libssl-dev python2 python clang libwayland-egl1 libwayland-dev libegl1-mesa-dev libgles2-mesa-dev libxcursor1 libxrandr2 libxi6
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
